
module.exports.ApiResponseCode = {
    OK: "OK",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    INVALID_PARAMETER_ERROR: "INVALID_PARAMETER_ERROR",
    UNAUTHORIZED: "UNAUTHORIZED",
    NOT_FOUND: "NOT_FOUND",
    ACCESS_DENIED: "AD0000",
    INVALID_PARAMETER_CODE: {
        IP0000: "IP0000",
        IP0001: "IP0001"
    },
    RECORD_DUPLICATION: "RECORD_DUPLICATION_ERROR",
    TRANSACTION_FAILED_ERROR: "TRANSACTION_FAILED_ERROR",
    DB_FETCH_RECORD_ERROR: "DB_FETCH_RECORD_ERROR",
    DB_UPDATE_RECORD_ERROR: "DB_UPDATE_RECORD_ERROR",
    DB_CREATE_RECORD_ERROR: "DB_CREATE_RECORD_ERROR",
};
